17:07:52.315 [main] WARN  ErrorPacket - Error: 1045-28000: Access denied for user 'slanity'@'61.75.21.155' (using password: YES)
17:07:53.321 [main] ERROR HikariPool - HikariPool-1 - Exception during pool initialization.
java.sql.SQLInvalidAuthorizationSpecException: (conn=7546) Access denied for user 'slanity'@'61.75.21.155' (using password: YES)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:293)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:378)
	at org.mariadb.jdbc.client.impl.StandardClient.authenticationHandler(StandardClient.java:460)
	at org.mariadb.jdbc.client.impl.StandardClient.handleAuthentication(StandardClient.java:342)
	at org.mariadb.jdbc.client.impl.StandardClient.setupConnection(StandardClient.java:159)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:127)
	at org.mariadb.jdbc.Driver.connect(Driver.java:75)
	at org.mariadb.jdbc.Driver.connect(Driver.java:104)
	at org.mariadb.jdbc.Driver.connect(Driver.java:29)
	at net.sf.log4jdbc.sql.jdbcapi.DriverSpy.connect(DriverSpy.java:401)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at util.HikariCPUtil.<clinit>(HikariCPUtil.java:33)
17:15:22.176 [main] INFO  HikariCPUtil - HikariDataSource (HikariPool-1)
